# Change these first
owner: rvladimirvm # Your GitHub organization or username, where this repository lives
repo: upptime-monitor # The name of this repository

sites:
  - name: rvladimir Blog Web Site
    url: https://www.rvladimir.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /upptime-monitor
  cname: monitor.rvladimir.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: rvladimir Monitor
  introTitle: "**Rvladimir** monitor"
  introMessage: This is a monitor for vladimir sites
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
